### ISSUE TITLE
[Question] How can we use it to completely mirror websites as we use wget ?

### ISSUE THREAD

**Issue by gurjit03** [Ineluki/telescopy#1]
With wget we have **--no-check-certificate -E -H -k -K -p -l 1** options to mirror a website completely, so with telescopy what config is needed to provide the same functionality ?
@Ineluki Will greatly appreciate your help.

**Comment by Ineluki** [comment]
I don't know all those wget parameters from memory, but the simplest config to mirror all on one host would be something like:

```javascript
var config = {
  "remote" : "https://www.example.com",		//starting url 
  "local" : "./Data/Mirror",				//folder to save to 
  "urlFilter" : [{
    "type" : "host",
    "value" : "www.example.com",			
    "nomatch" : false						//limit us to this domain 
  },true]									//get everything else 
};
```

I recommend reading up on the filter rules section since that's the most important part.
